


const maximum = prompt(" Enter the Maximum number:- "); // Tells the user to Enter the maximum number which means range::
const random = Math.floor( Math.random()* maximum) + 1; // This generates a Random number:- 

let predict = ( " Guess any number you want:- ");

while(true){
    if ( predict == "exit"){
        console.log(" You have Exited the game ");
        break;
    }

    if ( predict == random){
        console.log(` You predicted a right number:- ${random} Congratulations!!`);
        break;
    } else if (predict != random){
        guess = prompt(" Your guess does not Matches to the Actual number generated by the System !!! ");
    } else if (predict < guess){
        console.log(" The number you have Guessed is Small, guess biger than that!!");
    } else if (guess > random){
        console.log(" The number you have guessed is a bit big, guess smaller than that");
    } else{
        console.log(" Play again");
    }

}
